In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
data_0 = pd.read_csv("c:/Users/plane/Desktop/everything/현대로템 AI 개발자 교육/1차 프로젝트/수집데이터/시각화자료데이터/수사단서/범죄의_수사단서_2022.csv")
data_1 = pd.read_csv("c:/Users/plane/Desktop/everything/현대로템 AI 개발자 교육/1차 프로젝트/수집데이터/시각화자료데이터/수사단서/범죄의_수사단서_2021.csv")
data_2 = 
data_3 = 
data_4 = 
data_5 = 
data_6 = 
data_7 = 
data_8 = 
data_9 = 
data_10 = 
data_11 = 
data_12 =

In [23]:
data_0

,죄종별(1),죄종별(2),2022,2022.1,2022.2,2022.3,2022.4,2022.5,2022.6,2022.7,2022.8,2022.9,2022.10,2022.11,2022.12,2022.13,2022.14,2022.15
0,죄종별(1),죄종별(2),계,현행범,신고,신고,신고,신고,신고,신고,신고,미신고,미신고,미신고,미신고,미신고,미신고,미신고
1,죄종별(1),죄종별(2),소계,소계,소계,피해자신고,고소,고발,자수,진정투서,타인신고,소계,불심검문,피해품발견,변사체,탐문정보,여죄,기타
2,계,소계,1482433,72630,1216044,545914,271626,52591,4017,224438,117458,193759,62495,626,291,6615,56329,67403
3,강력범죄,소계,24954,2569,21710,9557,8438,103,66,811,2735,675,16,1,47,181,59,371
4,강력범죄,살인기수,275,47,154,16,17,5,18,1,97,74,-,-,44,2,2,26
5,강력범죄,살인미수등,427,208,202,59,61,2,6,1,73,17,2,-,-,1,2,12
6,강력범죄,강도,516,90,398,290,59,-,-,11,38,28,-,-,1,9,8,10
7,강력범죄,강간,5467,286,4937,1521,2591,25,11,231,558,244,-,-,2,58,20,164
8,강력범죄,유사강간,947,50,870,287,440,6,2,35,100,27,-,-,-,13,6,8
9,강력범죄,강제추행,15864,1457,14167,6873,5148,62,21,518,1545,240,13,1,-,91,17,118
10,강력범죄,기타 강간·강제추행등,225,15,200,68,93,-,-,8,31,10,-,-,-,4,-,6
11,강력범죄,방화,1233,416,782,443,29,3,8,6,293,35,1,-,-,3,4,27
12,절도범죄,소계,182270,3296,163408,153874,3452,105,120,4062,1795,15566,178,391,0,975,12795,1227
13,폭력범죄,소계,245286,29432,213412,161019,29269,336,185,9146,13457,2442,17,32,16,332,221,1824
14,폭력범죄,상해,26806,3429,23078,14255,5680,30,25,608,2480,299,-,3,10,53,11,222
15,폭력범죄,폭행,125217,16013,108130,85839,12280,71,90,2054,7796,1074,9,17,6,71,22,949
16,폭력범죄,체포・감금,1145,180,948,447,320,14,1,33,133,17,-,-,-,2,2,13
17,폭력범죄,협박,21567,4256,17026,10846,4610,42,15,756,757,285,4,1,-,18,12,250
18,폭력범죄,약취・유인,276,20,245,111,82,4,-,8,40,11,-,-,-,2,1,8
19,폭력범죄,폭력행위등,6745,484,6038,3838,1181,31,7,185,796,223,2,1,-,107,17,96
20,폭력범죄,공갈,6904,38,6676,1563,1276,28,3,3729,77,190,1,-,-,66,83,40
21,폭력범죄,손괴,56626,5012,51271,44120,3840,116,44,1773,1378,343,1,10,-,13,73,246
22,지능범죄,소계,405105,5457,394092,88136,127905,5817,558,169468,2208,5556,103,112,0,904,1607,2830
23,지능범죄,직무유기,1550,0,1543,1,1227,289,-,26,-,7,-,-,-,5,1,1
24,지능범죄,직권남용,1792,0,1777,3,1514,227,-,29,4,15,-,-,-,7,1,7
25,지능범죄,증수뢰,320,0,229,1,56,119,1,48,4,91,-,-,-,67,1,23
26,지능범죄,통화,452,2,433,108,2,48,-,132,143,17,-,1,-,3,-,13
27,지능범죄,문서・인장,11259,81,10545,298,6324,1349,11,1959,604,633,55,2,-,69,235,272
28,지능범죄,유가증권인지,58,2,53,7,27,4,-,3,12,3,-,-,-,-,-,3
29,지능범죄,사기,325848,5145,316451,47782,102453,2171,478,162610,957,4252,34,8,-,592,1291,2327
30,지능범죄,횡령,60220,227,59524,39927,13532,952,66,4570,477,469,14,101,-,113,75,166
31,지능범죄,배임,3606,0,3537,9,2770,658,2,91,7,69,-,-,-,48,3,18
32,풍속범죄,소계,27113,1560,21262,4584,8654,298,64,5151,2511,4291,79,2,0,500,365,3345
33,풍속범죄,성풍속범죄,22650,1175,19464,4329,8621,176,46,4914,1378,2011,70,2,0,181,214,1544
34,풍속범죄,도박범죄,4463,385,1798,255,33,122,18,237,1133,2280,9,-,0,319,151,1801
35,특별경제범죄,소계,48615,7156,39385,8423,17478,4010,72,8341,1061,2074,140,20,0,295,543,1076
36,마약범죄,소계,10331,358,2244,201,26,201,484,163,1169,7729,211,6,3,1154,1029,5326
37,보건범죄,소계,17749,280,15355,532,518,8045,18,1092,5150,2114,101,0,4,97,445,1467
38,환경범죄,소계,3477,9,3065,43,79,2578,8,156,201,403,20,0,0,37,253,93
39,교통범죄,소계,241029,1853,154085,84493,820,6822,2101,473,59376,85091,54662,16,63,67,85,30198
40,노동범죄,소계,714,1,353,9,37,196,1,83,27,360,1,0,0,41,276,42
41,안보범죄,소계,219,0,76,13,24,23,2,7,7,143,2,0,0,33,50,58
42,선거범죄,소계,2969,65,2563,111,270,1290,3,389,500,341,0,8,0,195,0,138
43,병역범죄,소계,4638,0,4616,0,5,4604,1,4,2,22,0,0,0,0,0,22
44,기타범죄,소계,267964,20594,180418,34919,74651,18163,334,25092,27259,66952,6965,38,158,1804,38601,19386

In [25]:
data_1

,죄종별(1),죄종별(2),2021,2021.1,2021.2,2021.3,2021.4,2021.5,2021.6,2021.7,2021.8,2021.9,2021.10,2021.11,2021.12,2021.13,2021.14,2021.15
0,죄종별(1),죄종별(2),계,현행범,신고,신고,신고,신고,신고,신고,신고,미신고,미신고,미신고,미신고,미신고,미신고,미신고
1,죄종별(1),죄종별(2),소계,소계,소계,피해자신고,고소,고발,자수,진정투서,타인신고,소계,불심검문,피해품발견,변사체,탐문정보,여죄,기타
2,계,소계,1429826,64875,1162173,568384,237353,44991,6089,193096,112260,202778,59770,675,342,8667,54485,78839
3,강력범죄,소계,22476,2268,19536,8170,8217,115,47,630,2357,672,4,-,47,212,74,335
4,강력범죄,살인기수,270,50,136,17,29,1,6,1,82,84,-,-,44,3,1,36
5,강력범죄,살인미수등,388,182,192,60,48,2,4,3,75,14,-,-,1,4,2,7
6,강력범죄,강도,495,87,353,244,58,1,1,9,40,55,-,-,-,12,28,15
7,강력범죄,강간,5263,275,4794,1469,2610,30,10,162,513,194,-,-,1,68,22,103
8,강력범죄,유사강간,814,57,730,231,390,3,4,29,73,27,-,-,-,14,-,13
9,강력범죄,강제추행,13962,1256,12449,5681,4991,75,17,413,1272,257,4,-,-,99,17,137
10,강력범죄,기타 강간·강제추행등,238,24,204,84,79,1,1,7,32,10,-,-,-,7,-,3
11,강력범죄,방화,1046,337,678,384,12,2,4,6,270,31,-,-,1,5,4,21
12,절도범죄,소계,166409,3460,149375,141121,3256,89,111,3158,1640,13574,188,494,-,1424,10249,1219
13,폭력범죄,소계,232661,27585,202393,153791,28980,302,192,6669,12459,2683,21,31,28,476,264,1863
14,폭력범죄,상해,28453,3452,24634,15487,6192,35,39,489,2392,367,6,1,11,85,6,258
15,폭력범죄,폭행,115942,15098,99743,80105,10916,48,81,1456,7137,1101,5,12,13,81,31,959
16,폭력범죄,체포・감금,1165,176,952,513,276,14,-,17,132,37,1,-,-,7,15,14
17,폭력범죄,협박,21058,3625,17059,10628,4979,38,23,692,699,374,5,2,-,34,69,264
18,폭력범죄,약취・유인,240,16,194,84,64,2,-,9,35,30,-,-,-,6,16,8
19,폭력범죄,폭력행위등,6484,496,5721,3588,1256,35,5,152,685,267,-,1,1,138,14,113
20,폭력범죄,공갈,5131,42,4898,1131,1269,23,3,2417,55,191,-,2,1,103,40,45
21,폭력범죄,손괴,54188,4680,49192,42255,4028,107,41,1437,1324,316,4,13,2,22,73,202
22,지능범죄,소계,361107,4412,347882,79592,111002,4748,432,150305,1803,8813,92,88,1,1472,3799,3361
23,지능범죄,직무유기,957,-,951,-,671,262,-,18,-,6,-,-,-,2,-,4
24,지능범죄,직권남용,875,-,841,2,685,128,-,25,1,34,-,-,-,21,-,13
25,지능범죄,증수뢰,402,1,153,1,33,76,-,38,5,248,-,-,-,58,164,26
26,지능범죄,통화,376,-,357,85,-,40,-,117,115,19,-,1,-,-,-,18
27,지능범죄,문서・인장,10472,48,9685,231,6169,1131,2,1739,413,739,52,-,-,51,459,177
28,지능범죄,유가증권인지,63,1,60,15,30,5,1,4,5,2,-,-,-,1,-,1
29,지능범죄,사기,294075,4138,283000,46326,88787,1768,369,144860,890,6937,26,15,1,1092,2853,2950
30,지능범죄,횡령,50421,224,49715,32926,12165,767,60,3431,366,482,14,71,-,200,53,144
31,지능범죄,배임,3466,-,3120,6,2462,571,-,73,8,346,-,1,-,47,270,28
32,풍속범죄,소계,23360,1626,15231,4295,5170,231,90,2682,2763,6503,65,2,-,1040,1503,3893
33,풍속범죄,성풍속범죄,16969,1112,13088,4002,5141,163,44,2427,1311,2769,56,2,-,345,619,1747
34,풍속범죄,도박범죄,6391,514,2143,293,29,68,46,255,1452,3734,9,-,-,695,884,2146
35,특별경제범죄,소계,40708,6201,32251,8081,13642,3683,84,5353,1408,2256,16,2,-,438,649,1151
36,마약범죄,소계,8088,275,2037,156,23,224,473,149,1012,5776,111,4,-,1218,525,3918
37,보건범죄,소계,16936,306,14296,422,432,8589,10,1374,3469,2334,171,-,1,137,276,1749
38,환경범죄,소계,3656,8,3346,44,78,2853,2,116,253,302,27,-,-,43,145,87
39,교통범죄,소계,308634,1741,214549,144501,770,3893,4322,456,60607,92344,52449,15,60,80,100,39640
40,노동범죄,소계,406,1,327,6,44,193,-,56,28,78,3,-,-,35,1,39
41,안보범죄,소계,206,2,78,9,31,21,-,10,7,126,-,-,1,39,8,78
42,선거범죄,소계,274,8,240,5,18,121,1,46,49,26,-,-,-,16,1,9
43,병역범죄,소계,1823,-,1807,-,4,1801,-,1,1,16,1,-,-,-,-,15
44,기타범죄,소계,243082,16982,158825,28191,65686,18128,325,22091,24404,67275,6622,39,204,2037,36891,21482