In [3]:
!pip install networkx

Requirement already satisfied: networkx in c:\users\plane\anaconda3\lib\site-packages (3.3)

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

UA = pd.read_csv('C:/ws/HD_Rotem2_pycode/Day10/우크라이나.csv', encoding = 'cp949')
UA.head(3)

,뉴스 식별자,일자,언론사,기고자,제목,통합 분류1,통합 분류2,통합 분류3,사건/사고 분류1,사건/사고 분류2,사건/사고 분류3,인물,위치,기관,키워드,특성추출(가중치순 상위 50개),본문,URL,분석제외 여부
0,4.100078e+06,20241230,뉴스핌,이나영,"소니드-소니드에이아이, 우크라이나 재건 겨냥 'AI 전방 경계시스템' 개발",IT_과학>모바일,IT_과학>보안,NaN,NaN,NaN,NaN,NaN,"우크라이나,전방,우범지역","KED-,소니드에이아이,애플,소니드-소니드에이아이,KED,소니드","소니드,소니드에이아이,우크라이나,재건,겨냥,AI,전방,경계,이나영,코스닥,상장사,소...","소니드에이아이,소니드,ai,브레인봇,구축비용,클레어픽셀,나노광학센,폭발물,cctv,...",[서울=뉴스핌] 이나영 기자=?코스닥상장사 소니드는 자회사 소니드에이아이를 통해 우...,https://www.newspim.com/news/view/20241230000585,NaN
1,2.100311e+06,20241230,서울경제,워싱턴=이태규 특파원,트럼프 취임 앞두고 美 하원의장 공백 재연되나,국제>미국_북미,국제>중남미,국제>유럽_EU,NaN,NaN,NaN,"트럼프,전,토머스,마이크 존슨,케빈 매카시,제임스 코머,스콧,존슨,도널드 트럼프,매카시","우크라이나,미국,펜실베이니아","폭스뉴스,하원,민주당,프리덤 코커스,공화당,의회,존슨","트럼프,취임,하원,의장,공백,재연,의장,내년,존슨,표결,내년,미국,하원,의장,선거,...","공화당,존슨,강경파,미국,더힐,매카시,하원의원",내년 초 미국 하원 의장 선거에서 공화당 내 강경파의 이탈로 지난해와 같은 의장 공...,http://www.sedaily.com/NewsView/2DIBMDPG7G,NaN
2,2.100351e+06,20241230,이투데이,김나은,"세계 각국 정상, 카터 전 미국 대통령 별세에 애도",정치>청와대,국제>미국_북미,국제>중남미,NaN,NaN,NaN,"에마뉘엘 마크롱,조 바이든,스타머,데이비드,키어,부시,쥐스탱 트뤼도,빌 클린턴,바이...","이스라엘,캐나다,프랑스,미국,인도,영국,소련,일본,워싱턴DC,버진아일랜드,애도,이집트","우크라이나,NBC방송,트위터,애도","정상,세계,각국,카터,별세,미국,대통령,애도,현직,미국,대통령,추모,물결,바이든,내...","카터,미국,각국,미국인,영국,트루스소셜,찰스,우크라이나,바이든,지도자,역사상,부시,...",[이투데이] 김나은 기자 (better68@etoday.co.kr)\n\n 전 현직...,https://www.etoday.co.kr/news/view/2433476,NaN

In [11]:
UA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   뉴스 식별자             20000 non-null  float64
 1   일자                 20000 non-null  int64
 2   언론사                20000 non-null  object
 3   기고자                18962 non-null  object
 4   제목                 20000 non-null  object
 5   통합 분류1             20000 non-null  object
 6   통합 분류2             19090 non-null  object
 7   통합 분류3             17313 non-null  object
 8   사건/사고 분류1          4331 non-null   object
 9   사건/사고 분류2          858 non-null    object
 10  사건/사고 분류3          231 non-null    object
 11  인물                 17577 non-null  object
 12  위치                 19992 non-null  object
 13  기관                 19966 non-null  object
 14  키워드                20000 non-null  object
 15  특성추출(가중치순 상위 50개)  20000 non-null  object
 16  본문                 20000 non-null  object
 17  URL                18831 non-null  object
 18  분석제외 여부            1060 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 2.9+ MB

In [21]:
UA.iloc[:, [4]]

                                               제목
0       소니드-소니드에이아이, 우크라이나 재건 겨냥 'AI 전방 경계시스템' 개발
1                       트럼프 취임 앞두고 美 하원의장 공백 재연되나
2                    세계 각국 정상, 카터 전 미국 대통령 별세에 애도
3           소니드 소니드에이아이, 우크라 재건 겨냥 AI 전방 경계시스템 개발
4             [신년사] 정태순 해운협회 회장 "불확실성에 도전정신으로 극복"
...                                           ...
19995          북러 위험한 결속에 한미일 경고했지만 ‘연내 정상회의’ 미지수
19996                     尹 “러 북 밀착 결코 좌시하지 않을 것”
19997   치솟는 원자재값 예타에 ‘발목’ 9개 노선 중 7곳 착공 못해 [심층기획]
19998  사실로 드러난 북한군 러시아 파병설, 지정학적 융합 가속화되나? [fn기고]
19999           美 대선 D-15...우리 기업 최대 관심은 '수출입 관세'

[20000 rows x 1 columns]

In [29]:
df = UA.iloc[:, [4]]
print(df)

                                               제목
0       소니드-소니드에이아이, 우크라이나 재건 겨냥 'AI 전방 경계시스템' 개발
1                       트럼프 취임 앞두고 美 하원의장 공백 재연되나
2                    세계 각국 정상, 카터 전 미국 대통령 별세에 애도
3           소니드 소니드에이아이, 우크라 재건 겨냥 AI 전방 경계시스템 개발
4             [신년사] 정태순 해운협회 회장 "불확실성에 도전정신으로 극복"
...                                           ...
19995          북러 위험한 결속에 한미일 경고했지만 ‘연내 정상회의’ 미지수
19996                     尹 “러 북 밀착 결코 좌시하지 않을 것”
19997   치솟는 원자재값 예타에 ‘발목’ 9개 노선 중 7곳 착공 못해 [심층기획]
19998  사실로 드러난 북한군 러시아 파병설, 지정학적 융합 가속화되나? [fn기고]
19999           美 대선 D-15...우리 기업 최대 관심은 '수출입 관세'

[20000 rows x 1 columns]

In [33]:
from konlpy.tag import Okt

okt = Okt()
nouns = okt.nouns()
nouns

NameError: name 'srt' is not defined